services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\SpeedyBundle\:
        resource: '../../../src/{Command,Client}'

    Answear\SpeedyBundle\ConfigProvider: ~

